name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: Build
        run: go build -v ./cmd/easy-dca
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
      - name: Test with coverage
        run: go test -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
      - name: Set VERSION var
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=dev" >> $GITHUB_ENV
          fi
      - name: Build Docker image
        run: docker build --build-arg VERSION=${VERSION} -t easy-dca . 